[global]
api_version = "V1"
post_up = "ip route add default via 192.168.1.1 dev eth2 src 192.168.1.254 table 101; ip rule add from 192.168.1.254 table 101"

[[cloudflare]]
ApiKey = ""
Email = ""
zoneID = ""
recordID = ""
recordName = ""
recordType = "A"
recordTTL = 1
recordProxied = false
GetIpCmd = "curl --interface eth1 --ipv4 https://api.ipify.org"

[[Cloudflare]]
ApiKey = ""
Email = ""
zoneID = ""
recordID = ""
recordName = ""
recordType = "A"
recordTTL = 1
recordProxied = false
GetIpCmd = "curl --interface eth1 --ipv4 https://api.ipify.org"
