api_version = "v1"

[[cloudflare]]
api_key = ""
email = ""
zone_id = ""
record_id = ""
record_name = ""
record_type = "A"
record_ttl = 1
record_proxied = false
CMD = "curl --interface eth1 --ipv4 https://api.ipify.org"

[[cloudflare]]
api_key = ""
email = ""
zone_id = ""
record_id = ""
record_name = ""
record_type = "AAAA"
record_ttl = 1
record_proxied = false
CMD = "curl --interface eth1 --ipv6 https://api.ipify.org"

