[global]
api_version = "V1"
post_up = "curl -s https://ip.yan-yun.com"

[[cloudflare]]
ApiKey = ""
Email = ""
zoneID = ""
recordID = ""
recordName = ""
recordType = "A"
recordTTL = 1
recordProxied = false
GetIpCmd = "curl --interface eth1 --ipv4 https://api.ipify.org"

[[Cloudflare]]
ApiKey = ""
Email = ""
zoneID = ""
recordID = ""
recordName = ""
recordType = "A"
recordTTL = 1
recordProxied = false
GetIpCmd = "curl --interface eth1 --ipv4 https://api.ipify.org"
